CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'uercan'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'uercan'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '1234';
FLUSH PRIVILEGES;